/**
 * Sample React Native App
 *
 * Generated by Nguyen Phuc Bao Chau
 * https://github.com/chaudev/react-native-base
 *
 * https://ischau.org
 *
 */

import React from 'react'
import {LogBox, StatusBar, View} from 'react-native'

import RootNavigator from '~/navigators/root'
import AppProvider from '~/provider/AppProvider'
import Signin from '~/views/auth/signin'

LogBox.ignoreAllLogs()

const App = () => {
  return (
    <View style={{flex: 1}}>
      <StatusBar translucent={true} backgroundColor="rgba(0,0,0,0)" />
      {/* <AppProvider>
        <RootNavigator />
      </AppProvider> */}
    </View>
  )
}

export default App
